### ISSUE TITLE
I'd like to run the UI with latest fontbakery from git

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery-ui#13]
At least as a means to facilitate my own work in improving the UI while also tweaking things on FB Core.

Not sure yet how to achieve that, though. Maybe by running `qfontbakery.py` directly from the command line (not using py2app) and having fontbakery installed form a git checkout with `pip install -e .` in the same virtualenv. I will try that...

**Comment by simoncozens** [comment]
Yes, that’s the right way to do it.

**Comment by felipesanches** [comment]
yes, it "worked" (except for the many issues I've posted today here LOL)
