### ISSUE TITLE
Incomplete list of profiles

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery-ui#15]
The list of profiles is hardcoded, which means it will (from time to time) be incomplete as it is right now (it lacks `universal`, for instance):
<img width="213" alt="Captura de Tela 2021-03-15 às 17 20 29" src="https://user-images.githubusercontent.com/213676/111216127-c58da780-85b2-11eb-86a0-822bf30c4232.png">

There should be some way to auto-populate this drop-down with all available profiles

**Comment by felipesanches** [comment]
And `universal` should be the default one!

**Comment by felipesanches** [comment]
but it should also remember the user's last choice

**Comment by simoncozens** [comment]
> There should be some way to auto-populate this drop-down with all available profiles

So first we need to solve https://github.com/googlefonts/fontbakery/issues/3188 so that when we walk the `fontbakery.profiles` namespace, we know which are "top-level profiles" that should appear in the list and which are just collections of checks.

**Comment by graphicore** [comment]
Do something simple. Put a module name `TOPLEVEL = True` in there and use it, or use a naming convention like `_`.

**Comment by simoncozens** [comment]
This is fixed in eacbbdc and fc21ce8
