### ISSUE TITLE
Table syntax is not properly rendered

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery-ui#21]
# I expected to see this:
| | /home/fsanches/gfonts/ofl/cantarell/Cantarell-Bold.ttf |
|:--- | ---:|
| Dehinted Size | 48.1kb |
| Hinted Size | 48.1kb |
| Increase | 40 bytes |
| Change | 0.1 % |

# but got this instead:
![Screenshot from 2021-03-15 19-34-25](https://user-images.githubusercontent.com/213676/111229926-8caafe00-85c5-11eb-8d88-33e4ed29f521.png)

**Comment by simoncozens** [comment]
Yeah, that doesn’t look like fontbakery is giving me correct HTML either.

**Comment by simoncozens** [comment]
This is now rendering correctly because of updates to fontbakery
